version: '3'

services:
  proxy:
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
